### ISSUE TITLE
SelectObjectContent no longer supported for S3

### ISSUE THREAD

**Issue by msaringer** [aws-samples/automatically-extending-amazon-s3-object-lock-retention#2]
[New customers are no longer able to use the SelectObjectContent action](https://docs.aws.amazon.com/AmazonS3/latest/API/API_SelectObjectContent.html): After careful consideration, we have made the decision to close new customer access to Amazon S3 Select and Amazon S3 Glacier Select, effective July 25, 2024. 

This is used to determine the number of rows in the Athena CSV in the ExtendObjLockS3BatchJobLambdaFunction code:
```
def select_query_function_csv(bucket, key, expression, fileheaderinfo, outputserialization):
    resp = s3Client.select_object_content
```
If SelectObjectContent is unavailable the request will fail: 

`[ERROR] ClientError: An error occurred (MethodNotAllowed) when calling the SelectObjectContent operation: The specified method is not allowed against this resource.`
`Traceback (most recent call last):`
  `File "/var/task/index.py", line 180, in lambda_handler
    my_csv_num_rows = select_query_function_csv(s3Bucket, s3Key, myexpression, my_fileheader_info, my_csv_output_serialization)`
  `File "/var/task/index.py", line 56, in select_query_function_csv
    resp = s3Client.select_object_content(`
 ` File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)`
  `File "/var/lang/lib/python3.11/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)`

This function is used to count the rows in the Athena output CSV so if it fails the batch job to extend the object lock will not be created.

**Comment by emmaylots-aws** [comment]
Thank you, this was fixed in the commit: https://github.com/aws-samples/automatically-extending-amazon-s3-object-lock-retention/commit/3999b32ae8b49d606a48951e82ba01789dfadaf4
